version: "3.8"

services:
    backend:
        build:
            target: production
        environment:
            - NODE_ENV=production
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: "512M"

    frontend:
        build:
            target: production
        environment:
            - NODE_ENV=production
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: "512M"
