version: "3.8"

services:
    backend:
        build:
            target: development
        volumes:
            - ./backend:/app
        environment:
            - NODE_ENV=development

    frontend:
        build:
            target: development
        volumes:
            - ./frontend:/app
        environment:
            - NODE_ENV=development
